### ISSUE TITLE
cacheManager 弱网或断网没有响应没有触发打印日志？

### ISSUE THREAD

**Issue by lqyc** [wechat-miniprogram/miniprogram-offline-demo#1]
1: createCacheManager的mode设置为always时，开发工具报错
![image](https://github.com/wechat-miniprogram/miniprogram-offline-demo/assets/26702382/239bf4c8-2eb4-4441-8c62-88a494498112)
2：createCacheManager的mode设置为weakNetwork时：开发工具模拟断网情况，没有触发打印日志
![image](https://github.com/wechat-miniprogram/miniprogram-offline-demo/assets/26702382/a02d1626-9e63-480d-804a-1c311c814265)
3: 代码片段
`// 创建缓存管理器
const cacheManager = wx.createCacheManager({
    origin: 'https://test.com/',
    mode: 'weakNetwork'
})
  
  // 添加请求规则
  cacheManager.addRule(/https:\/\/(?:.*)/ig) // 表示所有 https 请求都匹配
  console.error('默认在弱网时调用 wx.request 即会触发');
  cacheManager.on('enterWeakNetwork', () => {
    console.error('enterWeakNetwork')
  })
  cacheManager.on('exitWeakNetwork', () => {
    console.error('exitWeakNetwork')
  })
 // 监听符合规则的 wx.request 请求，默认在弱网时调用 wx.request 即会触发
  cacheManager.on('request', evt => {
    console.error('弱网时调用 ');
    return new Promise((resolve, reject) => {
      // 匹配是否存在缓存
      const matchRes = cacheManager.match(evt)
  
      if (matchRes && matchRes.data) {
        // 使用缓存返回
        resolve(matchRes.data)
      } else {
        // 没有匹配到缓存
        reject({errMsg: `catch not found: ${evt.url}`})
      }
    })
  })
`

**Comment by JuneAndGreen** [comment]
工具的模拟在这里：
<img width="347" alt="image" src="https://github.com/wechat-miniprogram/miniprogram-offline-demo/assets/7931744/ac74f78c-fc64-43f8-9025-0c5ff2aba768">

不是 network 面板那个。

另外关于弱网相关，工具只是做了有限支持，建议直接上真机调试。比如像弱网下的授权弹窗等就只有真机才能体验。

**Comment by JuneAndGreen** [comment]
后续此类非 demo 本身的问题建议统一发到小程序社区，会有专门同学来跟进，此处我就先关闭了。

**Comment by lqyc** [comment]
> 后续此类非 demo 本身的问题建议统一发到小程序社区，会有专门同学来跟进，此处我就先关闭了。

小程序也发了，没有效的回应。。。。

**Comment by lqyc** [comment]
> 工具的模拟在这里： <img alt="image" width="347" src="https://user-images.githubusercontent.com/7931744/279631108-ac74f78c-fc64-43f8-9025-0c5ff2aba768.png">
> 
> 不是 network 面板那个。
> 
> 另外关于弱网相关，工具只是做了有限支持，建议直接上真机调试。比如像弱网下的授权弹窗等就只有真机才能体验。

感恩，换了模拟方式可以正常进入弱网模式了，但是原来网络正常时请求到的图片，在弱网模式下没有被缓存到吗？
<img width="1190" alt="image" src="https://github.com/wechat-miniprogram/miniprogram-offline-demo/assets/26702382/3279ba43-4b9e-4f1e-8f87-d81a5a66976c">

**Comment by JuneAndGreen** [comment]
> > 工具的模拟在这里： <img alt="image" width="347" src="https://user-images.githubusercontent.com/7931744/279631108-ac74f78c-fc64-43f8-9025-0c5ff2aba768.png">
> > 不是 network 面板那个。
> > 另外关于弱网相关，工具只是做了有限支持，建议直接上真机调试。比如像弱网下的授权弹窗等就只有真机才能体验。
> 
> 感恩，换了模拟方式可以正常进入弱网模式了，但是原来网络正常时请求到的图片，在弱网模式下没有被缓存到吗？ <img alt="image" width="1190" src="https://user-images.githubusercontent.com/26702382/279853102-3279ba43-4b9e-4f1e-8f87-d81a5a66976c.png">

工具 http 缓存的话，归工具那边的同事负责，还是要在社区那边找工具值班同学问问才行。cacheManager 是基础库层面的实现，主要是拦截 wx.request 请求，http 缓存的话是客户端层面直接支持的能力。
