### ISSUE TITLE
demo存在异常

### ISSUE THREAD

**Issue by sparrow-team** [wechat-miniprogram/miniprogram-offline-demo#3]
我下载并且按照文档打开了这个demo，但是在开发者工具中正常打开项目并没有看到cachemanager起作用
尝试流程：
1、正常网络打开页面
2、切换network为离线
3、刷新页面

**Comment by JuneAndGreen** [comment]
这是针对移动端的优化，请尽量在手机端尝试。

工具侧只有非常简单的模拟，模拟开关在这里（可以切到 offline 看看）：
<img width="236" alt="image" src="https://github.com/wechat-miniprogram/miniprogram-offline-demo/assets/7931744/55754d62-ee7b-4a74-ba9b-7926e7cff7ac">
