### ISSUE TITLE
没有网络冷启动进入小程序wx.getLocation无效

### ISSUE THREAD

**Issue by Kai-web** [wechat-miniprogram/miniprogram-offline-demo#4]
没有网络，冷启动进入小程序（小程序没有在后台运行的情况下）wx.getLocation这类需要授权授权的api无法获取到坐标，偶尔一两次能获取，但是要等待很长时间，

**Comment by JuneAndGreen** [comment]
这里只是个 demo 项目，具体问题请提到微信开放社区，会有相关同学来跟进。
